engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
    - "app/**/*"
    - "lib/**/*"
    - "**.rb"
exclude_paths:
  - "public/**/*"
  - "spec/**/*"
  - "vendor/**/*"
