AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - lib/tasks/**/*
    - spec/**/*

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
