require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
  NewCops: enable

Layout/LineLength:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - lib/tasks/**/*
    - spec/**/*

Rails/HelperInstanceVariable:
  Exclude:
    - app/helpers/application_helper.rb

RSpec/MultipleExpectations:
  Max: 3

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
