language: ruby
cache: bundler
rvm:
  - 2.4.0
before_install:
  - gem update --system
before_script:
  - psql -c 'create database sixtwothree_test;' -U postgres
  - cp config/database.yml{.example,}
  - cp config/secrets.yml{.example,}
after_success:
  - bundle exec codeclimate-test-reporter
notifications:
  email: false
  slack: sixtwothree:yATLmjTW15443qR7jbCWr3RO
