version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  install-deps:
    executor:
      name: ruby/default
      tag: 2.4.9
    steps:
      - checkout
      - run:
          name: Install PostgreSQL client
          command: sudo apt install -y postgresql-client
      - ruby/install-deps

workflows:
  version: 2
  default:
    jobs:
      - install-deps
