version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

references:
  executor: &executor
    name: ruby/default
    tag: 2.4.9

jobs:
  install-deps:
    executor: *executor
    steps:
      - checkout
      - run:
          name: Install PostgreSQL development libraries
          command: |
            sudo apt update
            sudo apt install -y libpq-dev
      - ruby/install-deps

  lint:
    executor: *executor
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run linting Rake tasks
          command: |
            bundle exec rubocop
            bundle exec brakeman

  test:
    docker:
      - image: cimg/ruby:2.4.9
      - image: circleci/postgres:9.4.22-alpine
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            sudo apt update
            sudo apt install -y nodejs tzdata
      - ruby/install-deps
      - run:
          name: Install CodeClimate test reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - run:
          name: Run default Rake task
          command: bundle exec rake
      - run:
          name: Upload coverage report to CodeClimate
          command: ./cc-test-reporter after-build

workflows:
  version: 2
  default:
    jobs:
      - install-deps
      - lint:
          requires:
            - install-deps
      - test:
          requires:
            - install-deps
