# Build sources
source: ./src
destination: ./public

# Gems
gems: ['jekyll-assets', 'uglifier']

# Site variables
title: sixtwothree.org
description: 'Online home to Jason Garber, one of the Internet’s top Jason Garbers.'
url: http://sixtwothree.org
repository_url: https://github.com/jgarber623/sixtwothree.org

# Permalink settings
permalink: /:categories/:title

# Assets
assets:
  css_compressor: sass
  gzip: false
  js_compressor: uglifier

# Authoring
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'strikethrough']

# Defaults
defaults:
  -
    scope:
      path: 'blog'
      type: 'post'
    values:
      layout: 'post'

# Author meta
author:
  name: Jason Garber
  email: jason@sixtwothree.org
  url: http://sixtwothree.org/

# License
license:
  title: Creative Commons Attribution-NonCommercial-ShareAlike 3.0
  url: http://creativecommons.org/licenses/by-nc-sa/3.0/
