- name: Bandcamp
  class: bandcamp
  url: https://bandcamp.com/jgarber

- name: CodePen
  class: codepen
  url: http://codepen.io/jgarber

- name: Delicious
  class: delicious
  url: https://delicious.com/jgarber

- name: Facebook
  class: facebook
  url: https://www.facebook.com/jgarber623

- name: Ficly
  class: ficly
  url: http://ficly.com/authors/jgarber

- name: Flickr
  class: flickr
  url: http://flickr.com/photos/jgarber

- name: GitHub
  class: github
  url: https://github.com/jgarber623

- name: Goodreads
  class: goodreads
  url: https://www.goodreads.com/jgarber623

- name: Huffduffer
  class: huffduffer
  url: https://huffduffer.com/jgarber

- name: Instagram
  class: instagram
  url: http://instagram.com/jgarber

- name: Instapaper
  class: instapaper
  url: https://www.instapaper.com/p/jgarber

- name: Keybase
  class: keybase
  url: https://keybase.io/jgarber

- name: Kickstarter
  class: kickstarter
  url: http://www.kickstarter.com/profile/jgarber

- name: Lanyrd
  class: lanyrd
  url: http://lanyrd.com/profile/jgarber

- name: Letterboxd
  class: letterboxd
  url: http://letterboxd.com/jgarber

- name: Medium
  class: medium
  url: https://medium.com/@jgarber

- name: npm
  class: npm
  url: https://www.npmjs.com/~jgarber

- name: Polar
  class: polar
  url: http://polarb.com/users/jgarber

- name: Rdio
  class: rdio
  url: http://www.rdio.com/people/jgarber

- name: Speaker Deck
  class: speakerdeck
  url: https://speakerdeck.com/jgarber

- name: Twitter
  class: twitter
  url: https://twitter.com/jgarber

- name: Vimeo
  class: vimeo
  url: https://vimeo.com/jgarber

- name: Untappd
  class: untappd
  url: https://untappd.com/user/jgarber

- name: VSCO Grid
  class: vsco
  url: http://jgarber.vsco.co/