name: CI

on:
  push:
    branches-ignore: [production]
  pull_request:
    branches-ignore: [production]
  workflow_call:
    secrets:
      CC_TEST_REPORTER_ID:
        required: true
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Brakeman static analysis
        run: bundle exec brakeman --no-pager --run-all-checks
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run bundler-audit
        run: bundle exec bundle-audit check --update
  lint:
    name: Lint
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop --require code_scanning --format progress --format CodeScanning::SarifFormatter --out rubocop.sarif
      - uses: github/codeql-action/upload-sarif@v2
        if: ${{ always() }}
        with:
          sarif_file: rubocop.sarif
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.4.22-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-retries 5
          --health-timeout 5s
          --mount type=tmpfs,destination=/var/lib/postgresql/data
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run RSpec
        run: bundle exec rspec --format RSpec::Github::Formatter
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/sixtwothree_org_test
      - uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
